version: '3'
services:
  backend:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A config.celery.celery_app worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis

  celery-beat:
    build: .
    command: celery -A config.celery.celery_app beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis